# Generated by Django 5.2.8 on 2025-11-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('tipo_tamal', models.CharField(max_length=100, verbose_name='Tipo de tamal')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad de tamales')),
                ('comentarios', models.TextField(blank=True, verbose_name='Comentarios / indicaciones')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LISTO', 'Listo'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pedido')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
